[fastp-json]
pattern_glob = "*.json"
content_regex = '''
{
	"summary": {
		"before_filtering": {
			"total_reads":.*'''

[fastp-html]
pattern_glob = "*.html"
content_regex = '''
<html><head><meta http-equiv="content-type" content="text/html;charset=.+" /><title>fastp report at .+</title><script src=.+></script>.*'''

[bismark-align]
pattern_glob = "*_[SP]E_report.txt"
content_regex = '''
Bismark report for:.*'''

[bismark-deduplicate]
pattern_glob = "*.deduplication_report.txt"
content_regex = '''

Total number of alignments analysed in.*'''

[bowtie2-paired]
pattern_glob = "*"
content_regex = '''
\d+ reads; of these:
\s+\d+ (100.00%) were paired; of these:'''

[bowtie2-unpaired]
pattern_glob = "*"
content_regex = '''
\d+ reads; of these:
\s+\d+ (100.00%) were unpaired; of these:'''
